### ISSUE TITLE
404 for Developer's Guide

### ISSUE THREAD

**Issue by bflynn-attivio** [attivio/searchui#6]
On the Developer's Guide for the searchui: 
https://github.com/attivio/searchui/blob/master/DevelopersGuide.md

There is reference to the Developer's Guide for searchui-frontend: https://github.com/attivio/searchui/blob/master/searchui-frontend/Developing.MD

Specifically, the reference to searchui-frontend is meant to enable developers to setup an environment which allows them to seamlessly review changes to light customizations of the searchui (i.e. logo changes, facet configurations, etc)

The link to the Developer's Guide for searchui-frontend is currently 404ing.

**Comment by antpanman** [comment]
I've fixed some links that broke due to renaming the sub-projects to remove the "searchui-". I think I've gotten tham all on develop and master, but if you see any more, let us know.
